### ISSUE TITLE
Cannot remove Cosmoz.TranslatableBehavior because workaround methods are needed

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-i18next#17]
In https://github.com/Neovici/cosmoz-i18next/pull/16 I have made an attempt to remove Cosmoz.TranslatableBehavior completely.

But the removal of the `_()` and other wrappers using this behavior in the component itself and other components using `cosmoz-i18next`fails, it complains that the functions are missing.

Example of `yarn lint` output:

```
<template>[[ _(input, t) ]]</template>
	            ~
cosmoz-t.html(5,14) warning [databind-with-unknown-property] - _ is not declared or used more than once. Did you mean: t
	<template>[[ _(input, t) ]]</template>
	            ~
cosmoz-t.html(5,14) warning [databinding-calls-must-be-functions] - _ is not a known method on cosmoz-t
```

How can I remove or alter the wrappers so they work without `Cosmoz.TranslatableBehavior`?

I assign @megheaiulian and @cristi on suggestion by @nomego.

**Comment by cristinecula** [comment]
Related https://github.com/Neovici/cosmoz-i18next/issues/19

**Comment by cristinecula** [comment]
Related https://github.com/Neovici/cosmoz-omnitable/pull/288

**Comment by nomego** [comment]
I think this is fixed now
