### ISSUE TITLE
Upgrade to latest i18next

### ISSUE THREAD

**Issue by cristinecula** [Neovici/cosmoz-i18next#25]
I tried upgrading to latest i18next when fixing https://github.com/Neovici/cosmoz-i18next/issues/18, but quickly ran into breaking changes, so instead I used the existing 1.* version (which is published to npm as i18next-client). 

Eventually we should upgrade to the latest i18next.

**Comment by nomego** [comment]
`warning @neovici/cosmoz-i18next > i18next-client@1.11.4: you can use npm install i18next from version 2.0.0`

**Comment by cristinecula** [comment]
The upgrade from v1.11 to v17 is not straightforward at all: https://www.i18next.com/misc/migration-guide
I will first add unit tests for the current version of cz-i18next and make sure I get enough test coverage and only then attempt to make the upgrade. This way I can ensure that we can easily upgrade on cosmoz-frontend.
